### ISSUE TITLE
error: Internal data stream error. 

### ISSUE THREAD

**Issue by saket424** [Serge3006/deepstream-restricted-zone-detection#2]
@Serge3006 
Thanks for this project and associated blog post https://medium.com/@chavezferia.justinian/nvidia-deepstream-for-ai-based-computer-vision-applications-in-production-5a5597566629

I am running your container on a ubuntu22.04 host on a nvidia 3070Ti amd ryzen9 laptop . I had to edit the model file path from /app/model/resnet10.caffemodel_b1_gpu0_int8.engine to /app/model/resnet10.caffemodel_b4_gpu0_int8.engine since the b1 file does not exist in the git repo

Here are the steps I followed

```
docker pull serge3006/deepstream-python-bindings:0.0.1
git clone https://github.com/Serge3006/deepstream-restricted-zone-detection
cd deepstream-restricted-zone-detection/app
docker build -f docker/app.Dockerfile -t deepstreamapp .
cd ..
edit the app/configs/detector_config.txt  and replace b1 with b4
docker run --gpus all -it --rm --net=host --privileged -v /tmp/.X11-unix:/tmp/.X11-unix -v `pwd`/app:/app -e DISPLAY=$DISPLAY -w /opt/nvidia/deepstream/deepstream-6.1 deepstreamapp:latest
```

Here is the output I get

```
2022-12-23 16:32:32.426 | INFO     | __main__:app:20 - Building the pipeline

(gst-plugin-scanner:19): GStreamer-WARNING **: 16:32:33.944: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_inferserver.so': libtritonserver.so: cannot open shared object file: No such file or directory

(gst-plugin-scanner:19): GStreamer-WARNING **: 16:32:33.946: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_udp.so': librivermax.so.0: cannot open shared object file: No such file or directory
2022-12-23 16:32:34.039 | INFO     | pipeline.pipeline:_build:148 - Creating pipeline
2022-12-23 16:32:34.039 | INFO     | pipeline.pipeline:_build:155 - Creating streammux
2022-12-23 16:32:34.072 | INFO     | pipeline.pipeline:_build:163 - Creating source_bin 0
2022-12-23 16:32:34.075 | INFO     | pipeline.pipeline:_build:163 - Creating source_bin 1
2022-12-23 16:32:34.075 | INFO     | pipeline.pipeline:_build:184 - Creating pgie
2022-12-23 16:32:34.106 | INFO     | pipeline.pipeline:_build:189 - Creating nvvidconv1
2022-12-23 16:32:34.107 | INFO     | pipeline.pipeline:_build:194 - Creating filter1
2022-12-23 16:32:34.107 | INFO     | pipeline.pipeline:_build:202 - Creating tiler
2022-12-23 16:32:34.108 | INFO     | pipeline.pipeline:_build:207 - Creating nvvidconv
2022-12-23 16:32:34.108 | INFO     | pipeline.pipeline:_build:212 - Creating nvosd
2022-12-23 16:32:34.114 | INFO     | pipeline.pipeline:_build:223 - Creating output sink
2022-12-23 16:32:34.115 | INFO     | pipeline.pipeline:_build:229 - At least one of the sources is live
2022-12-23 16:32:34.115 | INFO     | pipeline.pipeline:_build:232 - Setting elements properties
2022-12-23 16:32:34.115 | INFO     | pipeline.pipeline:_build:242 - WARNING: Overriding infer-config batch size 1 with number of sources 2
2022-12-23 16:32:34.115 | INFO     | pipeline.pipeline:_build:257 - Adding elements to Pipeline
2022-12-23 16:32:34.115 | INFO     | pipeline.pipeline:_build:268 - Linkink elements in the pipeline
2022-12-23 16:32:34.116 | INFO     | __main__:app:29 - Starting pipeline
2022-12-23 16:32:34.117 | INFO     | pipeline.pipeline:run:307 - Running pipeline
amdgpu: unknown (family_id, chip_external_rev): (146, 32)
libEGL warning: DRI2: failed to create dri screen
amdgpu: unknown (family_id, chip_external_rev): (146, 32)
libEGL warning: DRI2: failed to create dri screen
WARNING: [TRT]: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
0:00:02.772350925    17 0x7f4bdc004240 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1900> [UID = 1]: deserialized trt engine from :/app/model/resnet10.caffemodel_b4_gpu0_int8.engine
INFO: ../nvdsinfer/nvdsinfer_model_builder.cpp:610 [Implicit Engine Info]: layers num: 3
0   INPUT  kFLOAT input_1         3x368x640       
1   OUTPUT kFLOAT conv2d_bbox     16x23x40        
2   OUTPUT kFLOAT conv2d_cov/Sigmoid 4x23x40         

0:00:02.772398817    17 0x7f4bdc004240 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2004> [UID = 1]: Use deserialized engine model: /app/model/resnet10.caffemodel_b4_gpu0_int8.engine
0:00:02.773043275    17 0x7f4bdc004240 INFO                 nvinfer gstnvinfer_impl.cpp:313:notifyLoadModelStatus:<primary-inference> [UID 1]: Load new model:/app/configs/detector_config.txt sucessfully
Traceback (most recent call last):
  File "/app/pipeline/deepstream/helpers.py", line 23, in decodebin_child_added
    Object.set_property("drop-on-latency", True)
TypeError: object of type `GstSoupHTTPSrc' does not have property `drop-on-latency'
Traceback (most recent call last):
  File "/app/pipeline/deepstream/helpers.py", line 23, in decodebin_child_added
    Object.set_property("drop-on-latency", True)
TypeError: object of type `GstSoupHTTPSrc' does not have property `drop-on-latency'
Using GPU 0 (NVIDIA GeForce RTX 3070 Ti Laptop GPU, 46 SMs, 1536 th/SM max, CC 8.6, ECC off)
Using GPU 0 (NVIDIA GeForce RTX 3070 Ti Laptop GPU, 46 SMs, 1536 th/SM max, CC 8.6, ECC off)
cuGraphicsGLRegisterBuffer failed with error(219) gst_eglglessink_cuda_init texture = 1
0:00:07.394131515    17      0x2380a80 WARN                 nvinfer gstnvinfer.cpp:2288:gst_nvinfer_output_loop:<primary-inference> error: Internal data stream error.
0:00:07.394150200    17      0x2380a80 WARN                 nvinfer gstnvinfer.cpp:2288:gst_nvinfer_output_loop:<primary-inference> error: streaming stopped, reason not-negotiated (-4)
2022-12-23 16:32:39.820 | ERROR    | pipeline.deepstream.common:bus_call:29 - gst-stream-error-quark: Internal data stream error. (1): gstnvinfer.cpp(2288): gst_nvinfer_output_loop (): /GstPipeline:pipeline0/GstNvInfer:primary-inference:
streaming stopped, reason not-negotiated (-4)
2022-12-23 16:32:40.028 | ERROR    | pipeline.deepstream.common:bus_call:29 - gst-stream-error-quark: Internal data stream error. (1): gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstBin:source-bin-0/GstURIDecodeBin:uri-decode-bin/GstSoupHTTPSrc:source:
streaming stopped, reason not-negotiated (-4)
2022-12-23 16:32:44.787 | ERROR    | pipeline.deepstream.common:bus_call:29 - gst-stream-error-quark: Internal data stream error. (1): gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstBin:source-bin-1/GstURIDecodeBin:uri-decode-bin/GstSoupHTTPSrc:source:
streaming stopped, reason not-negotiated (-4)

```

Any help on What am I doing wrong ? Thanks

**Comment by saket424** [comment]
@Serge3006 
I tried the same steps on a different computer with a 3080ti Nvidia GPU and PopOS 22.04 and nvidia-docker2 and it appears to be working. Closing issue.

**Comment by saket424** [comment]
Closing issue

**Comment by saket424** [comment]
@Serge3006 
Thanks for the OpenGL grep tip. After I did what you suggested, it works on the laptop also. It was previously using the built-in Intel or AMD integrated graphics driver and this resulted in the data stream error

```
sudo prime-select nvidia
sudo reboot
sudo apt install mesa-utils (for glxinfo -- works only for intel branded cpu)

#nvidia-settings should work on both AMD and Intel processors unlike glxinfo
anand@l5i:~$ nvidia-settings -g | grep OpenGL
  OpenGL vendor string: NVIDIA Corporation
  OpenGL renderer string: NVIDIA GeForce RTX 3070 Ti Laptop GPU/PCIe/SSE2
  OpenGL version string: 4.6.0 NVIDIA 525.60.11
  OpenGL extensions:
anand@l5i:~$
anand@l5i:~$ glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 3070 Ti Laptop GPU/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 525.60.11
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 525.60.11
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 525.60.11
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
anand@l5i:~$ 
```
